### ISSUE TITLE
I can't get 'gem rdoc --all --overwrite' to reformat using hanna

### ISSUE THREAD

**Issue by MarskalGroup** [rdoc/hanna-nouveau#14]
In Windows 10 using pik with ruby 2.2.5 (other versions as well, same problem);

I added to my .gemrc file:
rdoc: -f hanna

I set my environment variable as follows:
RDOCOPT=-f hanna

I rebooted and ran:
gem rdoc --all --overwrite

then I typed:
gem server

Then I browsed:
http://localhost:8808

I don't see the nice hanna format, instead I see the format defined as:

Generated by RDoc 5.0.0.
Based on Darkfish by Michael Granger.

when i simply run rdoc in my gem directory, it all works beautifully for my wip gem, but not installed gems

Note: I am new to RDoc

Thanks!

**Comment by jeremyevans** [comment]
This seems unlikely to be a problem specific to hanna.  Have you used the same approach with another alternative RDoc template library and had that work?

**Comment by MarskalGroup** [comment]
I have not tried rdoc formatter alternatives. Can you recommend an alternative that is most similar to yours for me to test the issue with?I decided to try and reinstall ruby and I got an 'Invalid options: -f hanna' error when installing the bundler (gem install bundle). Maybe this is part of my problem?I attached the error.Thanks!


-------- Original Message --------
Subject: Re: [rdoc/hanna-nouveau] I can't get 'gem rdoc --all
--overwrite' to reformat using hanna (#14)

**Comment by jeremyevans** [comment]
Unfortunately, I'm not sure what other alternative formatters exist for current rdoc.  There was https://github.com/evan/allison, but it seems to be well out of date.  You could try `-f pot`, since rdoc seems to ship that one, but I've no experience with it.

Also, I can't see the error you uploaded, since it looks like GitHub Issue's email handling does not extend to attachments.  However, if you were reinstalling ruby, and you used `-f hanna` before the hanna-nouveau gem was installed, that would explain the error.

**Comment by MarskalGroup** [comment]
Ok. Thanks for your help.Local documentation of gems is not of great importance to me. I thought maybe I was just missing something simple.


-------- Original Message --------
Subject: Re: [rdoc/hanna-nouveau] I can't get 'gem rdoc --all
--overwrite' to reformat using hanna (#14)

**Comment by jeremyevans** [comment]
This is a rubygems issue, they force darkfish on you: https://github.com/rubygems/rubygems/blob/45966be372d85520630143090b82b455d287cec6/lib/rubygems/rdoc.rb#L229

**Comment by pjaspers** [comment]
They're still doing this: https://github.com/ruby/ruby/blob/master/lib/rdoc/rubygems_hook.rb#L198C1-L199C1

(Caught me by surprise to see darkfish still generating the docs when I ran `gem rdoc --all --overwrite` even after setting hanna as the default in my .gemrc)
